services:
  mysql:
    image: mysql:8.0
    container_name: sebelas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sebelas_catalog
      MYSQL_USER: sebelas
      MYSQL_PASSWORD: sebelas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  postgres:
    image: postgres:16
    container_name: sebelas-postgres
    environment:
      POSTGRES_USER: sebelas
      POSTGRES_PASSWORD: sebelas
      POSTGRES_DB: sebelas_orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: sebelas-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  postgres_data:
